### ISSUE TITLE
cannot import name '_lazy_import' from 'torchvision.extension'

### ISSUE THREAD

**Issue by student-t** [deep-learning-with-pytorch/dlwpt-code#21]
2_birds_airplanes.ipynb gives the error message. Possibility version mismatch. I'm using 0.4.0. Which version should I be using?

**Comment by elistevens** [comment]
The book was tested with torch 1.4 and IIRC that implies torchvision 0.5.0.  Try those versions?

**Comment by student-t** [comment]
Thanks. It worked on 1.4.0 but not the latest version. I downgraded and it worked.

**Comment by lantiga** [comment]
@student-t I'm testing with pytorch 1.6.0 and 0.7.0 but I can't reproduce the issue. What is the line that was triggering the error for you?
